
CREATE TABLE images(
    id INT AUTO_INCREMENT PRIMARY KEY,
    story_id INT NOT NULL,
    image BLOB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENt_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    CONSTRAINT fk_imagesstory
    FOREIGN KEY (story_id)
    REFERENCES story(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);